export const enum PlayersState {
  NOOP,
  WAIT_DEL,
  WAIT_FNAME,
  WAIT_LNAME,
  WAIT_CNTRY,
  WAIT_DOB,
  WAIT_ADD,
  WAIT_TEAM_ID,
  WAIT_PLAYER_ID,
  WAIT_ADD_TO_TEAM,
  WAIT_DEL_FROM_TEAM,
  WAIT_PLAYER_TO_ADD,
  WAIT_PLAYER_TO_DEL
}
